# tasks file for setup role
 
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - nodejs
      - npm

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
  
- name: Create directory for backend
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory


- name: copy archived files to local server
  become: true
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact
  command: "tar -xzf /home/ubuntu/backend/artifact.tar.gz -C /home/ubuntu/backend"
  become: true

- name: Install dependencies and build package
  become: true
  shell: |
    cd /home/ubuntu/backend && npm install && npm run build

- name: start backend server
  become: yes
  shell: |
    cd /home/ubuntu/backend && pm2 start npm -- start

    
    