# tasks file for setup role

- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - nodejs
      - npm

- name: Extract artifact and move backend directory
  command: |
    tar -xvf artifact.tar.gz -C backend/
    mv backend ~/      

- name: Install npm
  become: yes
  command: npm install

- name: stop default with pm2
  become: yes
  command: pm2 stop default

- name: start web server
  become: yes
  command: pm2 start npm -- start
    
    