# tasks file for setup role
 
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - nodejs
      - npm

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
  
- name: Create directory for backend
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory


- name: copy archived files to local server
  become: true
  copy: 
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact
  command: "tar -xzf /home/ubuntu/backend/artifact.tar.gz -C /home/ubuntu/backend"
  become: true

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/backend && npm install

- name: start backend server
  become: yes
  shell: |
    cd /home/ubuntu/backend && pm2 stop default && npm start npm -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"


    
    