# tasks file for setup role

- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - nodejs
      - npm

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
  
- name: Create directory for web
  become: true
  file:
    path: ~/web
    state: directory

- name: copy archived files to local server
  become: true
  copy: 
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Unarchive files
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web
    copy: no    

- name: Install npm
  become: yes
  command: npm install

- name: stop default with pm2
  become: yes
  command: pm2 stop default

- name: start web server
  become: yes
  command: |
    cd ~/web
    pm2 start npm -- start

    
    